package examples;
// Generated Dec 24, 2016 1:58:15 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LoaiPhong_POJO generated by hbm2java
 */
@Entity
@Table(name="TBLLOAIPHONG"
)
public class LoaiPhong_POJO  implements java.io.Serializable {


     private String MaLP;
     private String LoaiPhong;
     private Integer SoGiuong;
     private double DonGia;
     private String GhiChu;

    public LoaiPhong_POJO() {
    }

	
    public LoaiPhong_POJO(String MaLP) {
        this.MaLP = MaLP;
    }
    public LoaiPhong_POJO(String MaLP, String LoaiPhong, Integer SoGiuong, double DonGia, String GhiChu) {
       this.MaLP = MaLP;
       this.LoaiPhong = LoaiPhong;
       this.SoGiuong = SoGiuong;
       this.DonGia = DonGia;
       this.GhiChu = GhiChu;
    }
   
     @Id 

    
    @Column(name="MALP", nullable=false, length=20)
    public String getMaLP() {
        return this.MaLP;
    }
    
    public void setMaLP(String MaLP) {
        this.MaLP = MaLP;
    }

    
    @Column(name="LOAIPHONG", length=20)
    public String getLoaiPhong() {
        return this.LoaiPhong;
    }
    
    public void setLoaiPhong(String LoaiPhong) {
        this.LoaiPhong = LoaiPhong;
    }

    
    @Column(name="SOGIUONG", length=10)
    public Integer getSoGiuong() {
        return this.SoGiuong;
    }
    
    public void setSoGiuong(Integer SoGiuong) {
        this.SoGiuong = SoGiuong;
    }

    
    @Column(name="DONGIA", length=10)
    public double getDonGia() {
        return this.DonGia;
    }
    
    public void setDonGia(double DonGia) {
        this.DonGia = DonGia;
    }

    
    @Column(name="GHICHU", length=50)
    public String getGhiChu() {
        return this.GhiChu;
    }
    
    public void setGhiChu(String GhiChu) {
        this.GhiChu = GhiChu;
    }




}


