/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examples;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Long
 */
public class QuanLyKhachHang extends javax.swing.JPanel {

    Date NgSinh;
    Date NgXai;
    String ngay;
    String ngayXai;

    /**
     * Creates new form QuanLyNhanVien
     */
    public QuanLyKhachHang() {
        initComponents();
        LoadDataToTable();
    }

    public void LoadDataToTable() {
        ArrayList<KhachHang> dsKH = new ArrayList<KhachHang>();
        dsKH = KhachHang_Controller.getDSKH();
        DefaultTableModel model = (DefaultTableModel) Table_KH.getModel();
        Object[] row = new Object[6];
        for (int i = 0; i < dsKH.size(); i++) {
            row[0] = dsKH.get(i).getMaKH();
            row[1] = dsKH.get(i).getTenKH();
            row[2] = dsKH.get(i).getNgSinhKH();
            row[4] = dsKH.get(i).getQuocTich();
            row[5] = dsKH.get(i).getDiaChi();
            row[3] = dsKH.get(i).getSDT();
            model.addRow(row);
        }
    }
    public void resetTable() {
        DefaultTableModel model = (DefaultTableModel) Table_KH.getModel();
        model.setRowCount(0);
        LoadDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Group_GioiTinh = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Text_MaKH = new javax.swing.JTextField();
        Text_TenKH = new javax.swing.JTextField();
        Text_SDT = new javax.swing.JTextField();
        Text_DiaChi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Text_QuocTich = new javax.swing.JTextField();
        Date_NS = new org.jdesktop.swingx.JXDatePicker();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Button_NhapLaiKH = new javax.swing.JButton();
        Button_SuaKH = new javax.swing.JButton();
        Button_XoaKH = new javax.swing.JButton();
        Button_ThemKH = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Combo_ChonTTKH = new javax.swing.JComboBox<>();
        Text_NhapTTTKKH = new javax.swing.JTextField();
        Button_TraCuuKH = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_KH = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUẢN LÝ KHÁCH HÀNG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(205, 205, 205))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THÔNG TIN KHÁCH HÀNG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 20))); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(750, 265));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Mã khách hàng");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Họ tên khách hàng");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Địa chỉ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Số điện thoại");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Ngày sinh");

        Text_MaKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Text_TenKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Text_SDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Text_DiaChi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Quốc tịch");

        Text_QuocTich.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Text_QuocTich.setToolTipText("");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Couple-icon.png"))); // NOI18N

        Button_NhapLaiKH.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_NhapLaiKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Edit_000000_25.png"))); // NOI18N
        Button_NhapLaiKH.setText("Nhập lại");
        Button_NhapLaiKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_NhapLaiKHMouseClicked(evt);
            }
        });

        Button_SuaKH.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_SuaKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Recycling_000000_25.png"))); // NOI18N
        Button_SuaKH.setText("Sửa");
        Button_SuaKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_SuaKHMouseClicked(evt);
            }
        });

        Button_XoaKH.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_XoaKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Minus_000000_25.png"))); // NOI18N
        Button_XoaKH.setText("Xóa");
        Button_XoaKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_XoaKHMouseClicked(evt);
            }
        });

        Button_ThemKH.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_ThemKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Plus_000000_25.png"))); // NOI18N
        Button_ThemKH.setText("Thêm");
        Button_ThemKH.setMaximumSize(new java.awt.Dimension(100, 33));
        Button_ThemKH.setPreferredSize(new java.awt.Dimension(87, 33));
        Button_ThemKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_ThemKHMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_ThemKH, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Button_XoaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Button_SuaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Button_NhapLaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_ThemKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_XoaKH)
                    .addComponent(Button_SuaKH)
                    .addComponent(Button_NhapLaiKH))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Text_TenKH)
                            .addComponent(Text_MaKH)
                            .addComponent(Date_NS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(Text_SDT, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(Text_QuocTich, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Text_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(Text_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(Text_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Text_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(Text_QuocTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Date_NS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Text_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jLabel11.setText("Tìm kiếm khách hàng theo:");

        Combo_ChonTTKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Combo_ChonTTKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Text_NhapTTTKKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Button_TraCuuKH.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_TraCuuKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Search_000000_25.png"))); // NOI18N
        Button_TraCuuKH.setText("Tra cứu");

        Table_KH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Họ tên khách hàng", "Ngày sinh", "Điện thoại", "Quốc tịch", "Địa chỉ"
            }
        ));
        Table_KH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_KHMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table_KH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Combo_ChonTTKH, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(Text_NhapTTTKKH, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(Button_TraCuuKH)
                        .addGap(41, 41, 41))
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Combo_ChonTTKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text_NhapTTTKKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_TraCuuKH))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Table_KHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_KHMouseClicked
        // TODO add your handling code here:
        int i = Table_KH.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) Table_KH.getModel();
        Text_MaKH.setText(model.getValueAt(i, 0).toString());
        Text_TenKH.setText(model.getValueAt(i, 1).toString());
        // get date from table
        ngay = model.getValueAt(i, 2).toString();
        //convert date 
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat myFormat = new SimpleDateFormat("yyyy-MM-dd");
        
        try {
            NgSinh = myFormat.parse(ngay);
        } catch (ParseException ex) {
            Logger.getLogger(QuanLyKhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }
        //output converted date
        ngayXai = sdf.format(NgSinh);
        NgXai = new Date(ngayXai);
        Date_NS.setDate(NgXai);
//       
        Text_QuocTich.setText(model.getValueAt(i, 4).toString());
        Text_DiaChi.setText(model.getValueAt(i, 5).toString());
        Text_SDT.setText(model.getValueAt(i, 3).toString());
    }//GEN-LAST:event_Table_KHMouseClicked

    private void Button_ThemKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_ThemKHMouseClicked
        // TODO add your handling code here:
        String MaKH = Text_MaKH.getText();
        String TenKH = Text_TenKH.getText();
        Date NgSinh = Date_NS.getDate();
        String SDT = Text_SDT.getText();
        String QuocTich = Text_QuocTich.getText();
        String DiaChi = Text_DiaChi.getText();
        KhachHang KH = new KhachHang(MaKH, TenKH,NgSinh,SDT,QuocTich,DiaChi); 
        KhachHang_Controller.themKH(KH);
        JOptionPane.showMessageDialog(jPanel4, "Thêm Khách Hàng Thành Công!!!");
        resetTable();
    }//GEN-LAST:event_Button_ThemKHMouseClicked

    private void Button_NhapLaiKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_NhapLaiKHMouseClicked
        // TODO add your handling code here:
        Text_MaKH.setText("");
        Text_TenKH.setText("");
        Text_SDT.setText("");
        Text_QuocTich.setText("");
        Text_DiaChi.setText("");
        System.out.println("date " + Date_NS.getDate());
        Date d = new Date("01/01/2016");
        Date_NS.setDate(d);
    }//GEN-LAST:event_Button_NhapLaiKHMouseClicked

    private void Button_XoaKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_XoaKHMouseClicked
        // TODO add your handling code here:
        String MaKH = Text_MaKH.getText();
         if (MaKH.equals("") == true){
             return;
         }
         else{
         JOptionPane tbXoa = new JOptionPane();
         int t = tbXoa.showConfirmDialog(jPanel4, "Bạn có chắc chắn muốn xóa?", "XÓA",JOptionPane.OK_OPTION);
         if (t == 0){
              KhachHang_Controller.xoaKH(MaKH);
               JOptionPane.showMessageDialog(jPanel4, "Xóa Khách Hàng Thành Công!!!");
               resetTable();
         }
         }
    }//GEN-LAST:event_Button_XoaKHMouseClicked

    private void Button_SuaKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_SuaKHMouseClicked
        // TODO add your handling code here:
        String MaKH = Text_MaKH.getText();
        String TenKH = Text_TenKH.getText();
        Date NgSinh = Date_NS.getDate();
        String DienThoai = Text_SDT.getText();
        String QuocTich = Text_QuocTich.getText();
        String DiaChi = Text_DiaChi.getText();
        KhachHang KH = new KhachHang(MaKH, TenKH, NgSinh, DienThoai, QuocTich,DiaChi);
         JOptionPane tbSua = new JOptionPane();
         int t = tbSua.showConfirmDialog(jPanel4, "Bạn có chắc chắn muốn sửa?", "SỬA",JOptionPane.OK_OPTION);
         if (t == 0){
              KhachHang_Controller.capnhatKH(KH);
              JOptionPane.showMessageDialog(jPanel4, "Sửa Khách Hàng Thành Công!!!","THÔNG BÁO",JOptionPane.INFORMATION_MESSAGE);             
              resetTable();
         }
    }//GEN-LAST:event_Button_SuaKHMouseClicked
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_NhapLaiKH;
    private javax.swing.JButton Button_SuaKH;
    private javax.swing.JButton Button_ThemKH;
    private javax.swing.JButton Button_TraCuuKH;
    private javax.swing.JButton Button_XoaKH;
    private javax.swing.JComboBox<String> Combo_ChonTTKH;
    private org.jdesktop.swingx.JXDatePicker Date_NS;
    private javax.swing.ButtonGroup Group_GioiTinh;
    private javax.swing.JTable Table_KH;
    private javax.swing.JTextField Text_DiaChi;
    private javax.swing.JTextField Text_MaKH;
    private javax.swing.JTextField Text_NhapTTTKKH;
    private javax.swing.JTextField Text_QuocTich;
    private javax.swing.JTextField Text_SDT;
    private javax.swing.JTextField Text_TenKH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
