/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examples;

import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class QuanLyTaiKhoan extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyTaiKhoan
     */
    public QuanLyTaiKhoan() {
        initComponents();
        LoadDataToTable();
    }
public void LoadDataToTable(){
        ArrayList<TaiKhoanDangNhap> dsTK = new ArrayList<TaiKhoanDangNhap>();       
        dsTK = TaiKhoanDangNhap_Controller.getDSTK();
        DefaultTableModel model = (DefaultTableModel) Table_TK.getModel();
        Object[] row = new Object[6];
        for (int i = 0 ; i< dsTK.size(); i++){
            row[0] = dsTK.get(i).getMaTK();
            row[1] = dsTK.get(i).getMaNV();
            row[2] = dsTK.get(i).getLoaiTK();
            row[3] = dsTK.get(i).getNgayTao();
            row[4] = dsTK.get(i).getUser();
            model.addRow(row);
        }
        ArrayList<Tblnhanvien>  dsNV = new ArrayList<Tblnhanvien>();       
        dsNV = NhanVien_Controller.getDSNV();
       
        for (int j =0 ; j < dsNV.size(); j ++){
            Combo_TK_MaNV.addItem( dsNV.get(j).getManv());
        }
   }
public void resetTable() {
        DefaultTableModel model = (DefaultTableModel) Table_TK.getModel();
        model.setRowCount(0);
        LoadDataToTable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Combo_TK_MaNV = new javax.swing.JComboBox<>();
        Text_TaoTK = new javax.swing.JTextField();
        Password_TaoMK = new javax.swing.JPasswordField();
        Button_ThemTK = new javax.swing.JButton();
        Button_XoaTK = new javax.swing.JButton();
        Button_SuaTK = new javax.swing.JButton();
        Button_NhapLaiTK = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Text_MaTK = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Combo_LoaiTK = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Combo_ThongTinTK = new javax.swing.JComboBox<>();
        Text_TimKiemTK = new javax.swing.JTextField();
        Button_TimKiemTK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_TK = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản Lý Tài Khoản");
        setSize(new java.awt.Dimension(770, 540));

        jPanel1.setPreferredSize(new java.awt.Dimension(770, 540));

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUẢN LÝ TÀI KHOẢN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THÔNG TIN TÀI KHOẢN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 20))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(770, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã nhân viên");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tên đăng nhập");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Mật khẩu");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/staff_login.png"))); // NOI18N

        Combo_TK_MaNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Text_TaoTK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Password_TaoMK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Button_ThemTK.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_ThemTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Plus_000000_25.png"))); // NOI18N
        Button_ThemTK.setText("Thêm");
        Button_ThemTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_ThemTKMouseClicked(evt);
            }
        });

        Button_XoaTK.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_XoaTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Cancel_000000_25.png"))); // NOI18N
        Button_XoaTK.setText("Xóa");
        Button_XoaTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_XoaTKMouseClicked(evt);
            }
        });

        Button_SuaTK.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_SuaTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Recycling_000000_25.png"))); // NOI18N
        Button_SuaTK.setText("Sửa");
        Button_SuaTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_SuaTKMouseClicked(evt);
            }
        });

        Button_NhapLaiTK.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_NhapLaiTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Edit_000000_25.png"))); // NOI18N
        Button_NhapLaiTK.setText("Nhập lại");
        Button_NhapLaiTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_NhapLaiTKMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Mã tài khoản");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Loại tài khoản");

        Combo_LoaiTK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiếp tân", "Admin", "Quản lý" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button_ThemTK, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Button_XoaTK, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Button_SuaTK, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Button_NhapLaiTK)
                        .addGap(41, 41, 41))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(26, 26, 26)
                                .addComponent(Text_MaTK))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(Combo_LoaiTK, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(30, 30, 30))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Combo_TK_MaNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Text_TaoTK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Password_TaoMK, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Combo_TK_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(Text_MaTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Text_TaoTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(Combo_LoaiTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Password_TaoMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button_ThemTK)
                            .addComponent(Button_XoaTK)
                            .addComponent(Button_SuaTK)
                            .addComponent(Button_NhapLaiTK))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jLabel6.setText("Tìm kiếm tài khoản theo:");

        Combo_ThongTinTK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Combo_ThongTinTK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Text_TimKiemTK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Button_TimKiemTK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_TimKiemTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Search_000000_25.png"))); // NOI18N
        Button_TimKiemTK.setText("Tìm kiếm");

        Table_TK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tài khoản", "Mã nhân viên", "Loại tài khoản", "Ngày tạo", "Tên đăng nhập"
            }
        ));
        Table_TK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_TKMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_TK);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Combo_ThongTinTK, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Text_TimKiemTK, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Button_TimKiemTK)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Combo_ThongTinTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text_TimKiemTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_TimKiemTK))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Table_TKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_TKMouseClicked
        // TODO add your handling code here:
        
        int i = Table_TK.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) Table_TK.getModel();
        Text_MaTK.setText(model.getValueAt(i, 0).toString());
        Combo_TK_MaNV.setSelectedItem(model.getValueAt(i, 1).toString());
        Combo_LoaiTK.setSelectedItem(model.getValueAt(i, 2).toString());
        Text_TaoTK.setText(model.getValueAt(i, 4).toString());
    }//GEN-LAST:event_Table_TKMouseClicked

    private void Button_ThemTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_ThemTKMouseClicked
        // TODO add your handling code here:
        String MaTK = Text_MaTK.getText();
        String MaNV = Combo_TK_MaNV.getSelectedItem().toString();
        String LoaiTK = Combo_LoaiTK.getSelectedItem().toString();
        String User  = Text_TaoTK.getText();
        String MatKhau  = Password_TaoMK.getText();
        
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        String da = sdf.format(date);
        Date Ngtao = new Date(da);
        TaiKhoanDangNhap TK = new TaiKhoanDangNhap(MaTK,MaNV,LoaiTK,User,MatKhau,Ngtao); 
        TaiKhoanDangNhap_Controller.themTK(TK);
        JOptionPane.showMessageDialog(jPanel3, "Đăng Kí Tài Khoản Thành Công!!!");
        resetTable();
    }//GEN-LAST:event_Button_ThemTKMouseClicked

    private void Button_NhapLaiTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_NhapLaiTKMouseClicked
        // TODO add your handling code here:
        Text_MaTK.setText("");
        Combo_LoaiTK.setSelectedIndex(0);
        Combo_TK_MaNV.setSelectedIndex(0);
        Text_TaoTK.setText("");
        Password_TaoMK.setText("");
    }//GEN-LAST:event_Button_NhapLaiTKMouseClicked

    private void Button_XoaTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_XoaTKMouseClicked
        // TODO add your handling code here:
        String MaTK = Text_MaTK.getText();
         if (MaTK.equals("") == true){
             return;
         }
         else{
         JOptionPane tbXoa = new JOptionPane();
         int t = tbXoa.showConfirmDialog(jPanel3, "Bạn có chắc chắn muốn xóa?", "XÓA",JOptionPane.OK_OPTION);
         if (t == 0){
              TaiKhoanDangNhap_Controller.xoaTK(MaTK);
               JOptionPane.showMessageDialog(jPanel3, "Xóa Tài Khoản Thành Công!!!");
               resetTable();
         }
         }
    }//GEN-LAST:event_Button_XoaTKMouseClicked

    private void Button_SuaTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_SuaTKMouseClicked
        // TODO add your handling code here:
        String MaTK = Text_MaTK.getText();
        String MaNV = Combo_TK_MaNV.getSelectedItem().toString();
        String LoaiTK = Combo_LoaiTK.getSelectedItem().toString();
        String User  = Text_TaoTK.getText();
        String MatKhau  = Password_TaoMK.getText();
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        String da = sdf.format(date);
        Date Ngtao = new Date(da);
        TaiKhoanDangNhap TK = new TaiKhoanDangNhap(MaTK, MaNV, LoaiTK, User, MatKhau,Ngtao);
         JOptionPane tbSua = new JOptionPane();
         int t = tbSua.showConfirmDialog(jPanel3, "Bạn có chắc chắn muốn sửa?", "SỬA",JOptionPane.OK_OPTION);
         if (t == 0){
              TaiKhoanDangNhap_Controller.capnhatTK(TK);
              JOptionPane.showMessageDialog(jPanel3, "Sửa Thông Tin Tài Khoản Thành Công!!!","THÔNG BÁO",JOptionPane.INFORMATION_MESSAGE);             
              resetTable();
         }
    }//GEN-LAST:event_Button_SuaTKMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyTaiKhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_NhapLaiTK;
    private javax.swing.JButton Button_SuaTK;
    private javax.swing.JButton Button_ThemTK;
    private javax.swing.JButton Button_TimKiemTK;
    private javax.swing.JButton Button_XoaTK;
    private javax.swing.JComboBox<String> Combo_LoaiTK;
    private javax.swing.JComboBox<String> Combo_TK_MaNV;
    private javax.swing.JComboBox<String> Combo_ThongTinTK;
    private javax.swing.JPasswordField Password_TaoMK;
    private javax.swing.JTable Table_TK;
    private javax.swing.JTextField Text_MaTK;
    private javax.swing.JTextField Text_TaoTK;
    private javax.swing.JTextField Text_TimKiemTK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
