package examples;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Long
 */
public class QuanLyThuephong extends javax.swing.JPanel {
//biến ngày thuê

    String ngaythue;
    Date Ngaythue;
    String sdngaythue;
    ///
    Date Ngay;
    String sdngay;
    //biến ngày trả
    Date Ngaytra;
    String ngaytra;
    String sdngaytra;

    String ngaysinh;
    Date SDNgaysinh;
    String sdngaysinh;
    Date NgSinh;
    //biến ngày den
    Date NgXai;
    String ngay;
    String ngayXai;

    /**
     * Creates new form QuanLyLoaiPhong
     */
    public QuanLyThuephong() {
        initComponents();
        LoadDataToTable();
    }

    public void LoadDataToTable() {
        ArrayList<ThuePhong_POJO> dsTP = new ArrayList<ThuePhong_POJO>();
        dsTP = ThuePhong_Controller.getDSThuePhong();
        //code gọi
        ThuePhong_Controller tp = new ThuePhong_Controller();
        String matp = tp.LayMaTP();
        ////set vào textbox
        Text_mathuephong.setText(matp);
        DefaultTableModel model = (DefaultTableModel) Table_Phongthue.getModel();
        Object[] row = new Object[5];
        for (int i = 0; i < dsTP.size(); i++) {
            row[0] = dsTP.get(i).getMaThuePhong();
            row[1] = dsTP.get(i).getMaPhong();
            row[2] = dateFormat(dsTP.get(i).getNgayThue().toString());
            row[3] = dateFormat(dsTP.get(i).getNgayTra().toString());
            row[4] = dsTP.get(i).getMaKH();
            model.addRow(row);
        }

        ArrayList<Phong> dsPhong = new ArrayList<Phong>();
        dsPhong = Phong_Controller.getDSPhong();

        for (int j = 0; j < dsPhong.size(); j++) {
            if (dsPhong.get(j).getTinhTrang().equals("Có Khách") == false) {
                Combo_MaPhong.addItem(dsPhong.get(j).getMaPhong());
            }
        }
        ArrayList<KhachHang> dsKH = new ArrayList<KhachHang>();
        dsKH = KhachHang_Controller.getDSKH();
        for (int j = 0; j < dsKH.size(); j++) {
            Combo_MaKH.addItem(dsKH.get(j).getMaKH());
        }
    }

    public void resetTable() {
        DefaultTableModel model = (DefaultTableModel) Table_Phongthue.getModel();
        model.setRowCount(0);
        LoadDataToTable();
    }

    public String dateFormat(String x) {
        //convert date 

        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("MM/dd/yyyy hh:mm:ss");
        java.text.SimpleDateFormat myFormat = new java.text.SimpleDateFormat("yyyy-MM-dd hh:mm:ss");

        try {
            NgSinh = myFormat.parse(x);
        } catch (ParseException ex) {
            Logger.getLogger(QuanLyKhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }
        //output converted date
        return ngayXai = sdf.format(NgSinh);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Text_mathuephong = new javax.swing.JTextField();
        Combo_MaPhong = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        Combo_MaKH = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Button_ThemP = new javax.swing.JButton();
        Button_XoaLP = new javax.swing.JButton();
        Button_SuaLP = new javax.swing.JButton();
        Button_NhapLaiLP = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Text_MaDP = new javax.swing.JTextField();
        Date_NgayTra = new com.lavantech.gui.comp.DateTimePicker();
        Date_NgayThue = new com.lavantech.gui.comp.DateTimePicker();
        jLabel7 = new javax.swing.JLabel();
        ComboBox_ChonTTPT = new javax.swing.JComboBox<>();
        Text_NhapTTTKPT = new javax.swing.JTextField();
        Button_TimPT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Phongthue = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUẢN LÝ THUÊ PHÒNG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(195, 195, 195))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THÔNG TIN THUÊ PHÒNG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 20))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Mã thuê phòng");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Mã phòng");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Ngày trả");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Ngày thuê");

        Text_mathuephong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Text_mathuephong.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Mã khách hàng ");

        Button_ThemP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_ThemP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Plus_000000_25.png"))); // NOI18N
        Button_ThemP.setText("Thêm");
        Button_ThemP.setPreferredSize(new java.awt.Dimension(100, 33));
        Button_ThemP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_ThemPMouseClicked(evt);
            }
        });

        Button_XoaLP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_XoaLP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Cancel_000000_25.png"))); // NOI18N
        Button_XoaLP.setText("Xóa");
        Button_XoaLP.setPreferredSize(new java.awt.Dimension(100, 33));
        Button_XoaLP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_XoaLPMouseClicked(evt);
            }
        });

        Button_SuaLP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_SuaLP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Recycling_000000_25.png"))); // NOI18N
        Button_SuaLP.setText("Sửa");
        Button_SuaLP.setPreferredSize(new java.awt.Dimension(100, 33));
        Button_SuaLP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_SuaLPMouseClicked(evt);
            }
        });

        Button_NhapLaiLP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_NhapLaiLP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Edit_000000_25.png"))); // NOI18N
        Button_NhapLaiLP.setText("Nhập lại");
        Button_NhapLaiLP.setPreferredSize(new java.awt.Dimension(100, 33));
        Button_NhapLaiLP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_NhapLaiLPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_ThemP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Button_XoaLP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Button_SuaLP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Button_NhapLaiLP, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_ThemP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_XoaLP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_SuaLP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_NhapLaiLP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/house_home.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Mã đặt phòng");

        Text_MaDP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Text_MaDPFocusLost(evt);
            }
        });
        Text_MaDP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Text_MaDPKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(51, 51, 51)
                                .addComponent(Combo_MaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Text_mathuephong, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                    .addComponent(Text_MaDP))))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Combo_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(Date_NgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Date_NgayThue, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Date_NgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel10)
                                .addComponent(Text_MaDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Combo_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(Text_mathuephong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel4)
                                .addComponent(Combo_MaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Date_NgayThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setText("Tìm kiếm phòng thuê theo:");

        ComboBox_ChonTTPT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComboBox_ChonTTPT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã thuê phòng" }));

        Text_NhapTTTKPT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Button_TimPT.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_TimPT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Search_000000_25.png"))); // NOI18N
        Button_TimPT.setText("Tìm kiếm");
        Button_TimPT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_TimPTMouseClicked(evt);
            }
        });

        Table_Phongthue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã thuê phòng", "Mã phòng", "Ngày thuê", "Ngày trả", "Mã khách hàng"
            }
        ));
        Table_Phongthue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_PhongthueMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Phongthue);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ComboBox_ChonTTPT, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(Text_NhapTTTKPT, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(Button_TimPT))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ComboBox_ChonTTPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text_NhapTTTKPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_TimPT))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Table_PhongthueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_PhongthueMouseClicked
        // TODO add your handling code here:

        int i = Table_Phongthue.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) Table_Phongthue.getModel();
        Text_mathuephong.setText(model.getValueAt(i, 0).toString());
        Combo_MaPhong.setSelectedItem(model.getValueAt(i, 1).toString());
        ngaythue = model.getValueAt(i, 2).toString();

        //convert date ngày thuê
//        sdngaythue =dateFormat(ngaythue);
        Ngaythue = new Date(ngaythue);
        Date_NgayThue.setDate(Ngaythue);
        ////
        ngaytra = model.getValueAt(i, 3).toString();
        //convert date ngày trả
//        sdngaytra =dateFormat(ngaytra);
        Ngaytra = new Date(ngaytra);
        Date_NgayTra.setDate(Ngaytra);
        Combo_MaKH.setSelectedItem(model.getValueAt(i, 4).toString());
        Button_ThemP.setEnabled(false);
    }//GEN-LAST:event_Table_PhongthueMouseClicked

    private void Button_NhapLaiLPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_NhapLaiLPMouseClicked
        // TODO add your handling code here:
        Text_MaDP.setText("");
        Combo_MaPhong.setSelectedIndex(0);
        Combo_MaKH.setSelectedIndex(0);
        Date date = new Date("9/30/2016");
        Date_NgayThue.setDate(date);
        Button_ThemP.setEnabled(true);
    }//GEN-LAST:event_Button_NhapLaiLPMouseClicked

    private void Button_ThemPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_ThemPMouseClicked
        // TODO add your handling code here:
        String MaTP = Text_mathuephong.getText();
        String MaPhong = Combo_MaPhong.getSelectedItem().toString();
        Date NgThue = Date_NgayThue.getDate();
        Date NgTra = Date_NgayTra.getDate();
        String MaKH = Combo_MaKH.getSelectedItem().toString();
        ThuePhong_POJO TP = new ThuePhong_POJO(MaTP, MaPhong, NgThue, NgTra, MaKH);
        ThuePhong_Controller.themThuePhong(TP);
        JOptionPane.showMessageDialog(jPanel2, "Thêm Phiếu Thuê Thành Công!!!");

        // set tinh trang phong
        ArrayList<Phong> dsPhong = new ArrayList<Phong>();
        dsPhong = Phong_Controller.getDSPhong();
        for (int i = 0; i < dsPhong.size(); i++) {
            if (dsPhong.get(i).getMaPhong().equals(MaPhong) == true) {
                dsPhong.get(i).setTinhTrang("Có Khách");
                Phong_Controller.capNhatPhong(dsPhong.get(i));
                TrangChu.getTinhTrangPhong().revalidate();
                TrangChu.getTinhTrangPhong().repaint();
                TrangChu.getTinhTrangPhong().doLayout();
            }
        }
        resetTable();
    }//GEN-LAST:event_Button_ThemPMouseClicked

    private void Button_XoaLPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_XoaLPMouseClicked
        // TODO add your handling code here:
        String MaTP = Text_mathuephong.getText();
        String MaPhong = Combo_MaPhong.getSelectedItem().toString();
        if (MaTP.equals("") == true) {
            return;
        } else {
            JOptionPane tbXoa = new JOptionPane();
            int t = tbXoa.showConfirmDialog(jPanel2, "Bạn có chắc chắn muốn xóa?", "XÓA", JOptionPane.OK_OPTION);
            if (t == 0) {
                ThuePhong_Controller.xoaThuePhong(MaTP);
                JOptionPane.showMessageDialog(jPanel2, "Xóa Phiếu Thuê Thành Công!!!");
                // set tinh trang phong
                ArrayList<Phong> dsPhong1 = new ArrayList<Phong>();
                dsPhong1 = Phong_Controller.getDSPhong();
                for (int i = 0; i < dsPhong1.size(); i++) {
                    if (dsPhong1.get(i).getMaPhong().equals(MaPhong) == true) {
                        dsPhong1.get(i).setTinhTrang("Trống");
                        Phong_Controller.capNhatPhong(dsPhong1.get(i));
                        TrangChu.getTinhTrangPhong().updateUI();
                    }
                }
                resetTable();
                Button_ThemP.setEnabled(true);
            }
        }
    }//GEN-LAST:event_Button_XoaLPMouseClicked

    private void Button_SuaLPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_SuaLPMouseClicked
        // TODO add your handling code here:
        String MaTP = Text_mathuephong.getText();
        String MaPhong = Combo_MaPhong.getSelectedItem().toString();
        Date NgThue = Date_NgayThue.getDate();
        Date NgTra = Date_NgayTra.getDate();
        String MaKH = Combo_MaKH.getSelectedItem().toString();
        ThuePhong_POJO TP = new ThuePhong_POJO(MaTP, MaPhong, NgThue, NgTra, MaKH);
        JOptionPane tbSua = new JOptionPane();
        int t = tbSua.showConfirmDialog(jPanel2, "Bạn có chắc chắn muốn sửa?", "SỬA", JOptionPane.OK_OPTION);
        if (t == 0) {
            ThuePhong_Controller.capnhatTP(TP);
            JOptionPane.showMessageDialog(jPanel2, "Sửa Thông Tin Thuê Phòng Thành Công!!!", "THÔNG BÁO", JOptionPane.INFORMATION_MESSAGE);
            resetTable();
            Button_ThemP.setEnabled(true);
        }
    }//GEN-LAST:event_Button_SuaLPMouseClicked

    private void Button_TimPTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_TimPTMouseClicked
        // TODO add your handling code here:
        if (Text_NhapTTTKPT.getText().equals("") == true) {
            resetTable();

        } else {
            if (ComboBox_ChonTTPT.getSelectedItem().equals("Mã thuê phòng") == true) {
                String MaTP = Text_NhapTTTKPT.getText();
                ArrayList<ThuePhong_POJO> dsTP = new ArrayList<ThuePhong_POJO>();

                dsTP = ThuePhong_Controller.getDSThuePhongTheoMa("MaTP", MaTP);
                if (dsTP.size() == 0) {
                    JOptionPane.showMessageDialog(null, "Không Có Thông Tin Thuê Phòng", "Lỗi", JOptionPane.ERROR_MESSAGE);
                } else {
                    DefaultTableModel model = (DefaultTableModel) Table_Phongthue.getModel();
                    Object[] row = new Object[5];
                    model.setRowCount(0);
                    for (int i = 0; i < dsTP.size(); i++) {
                        row[0] = dsTP.get(i).getMaThuePhong();
                        row[1] = dsTP.get(i).getMaPhong();
                        row[2] = dateFormat(dsTP.get(i).getNgayThue().toString());
                        row[3] = dateFormat(dsTP.get(i).getNgayTra().toString());
                        row[4] = dsTP.get(i).getMaKH();
                        model.addRow(row);
                    }
                    JOptionPane.showMessageDialog(jPanel2, "Tìm Thấy Thông Tin Thuê Phòng!!!", "THÔNG BÁO", JOptionPane.INFORMATION_MESSAGE);

                }
            }
        }
    }//GEN-LAST:event_Button_TimPTMouseClicked

    private void Text_MaDPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Text_MaDPKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String MaDP = Text_MaDP.getText();
            ArrayList<DatPhong> dsTP = new ArrayList<DatPhong>();
            dsTP = DatPhong_Controller.getDSDP();
            for (int i = 0; i < dsTP.size(); i++) {
                if (MaDP.equals(dsTP.get(i).getMaDK()) == true) {
                    Combo_MaPhong.setSelectedItem(dsTP.get(i).getMaPhong());
                    Combo_MaKH.setSelectedItem(dsTP.get(i).getMaKH());
                    
                    String ngaythue1 = dsTP.get(i).getNgayDK().toString();
                    String NgayThue1 = dateFormat(ngaythue1);
                    Date Ngaythue2 = new Date(NgayThue1);
                    Date_NgayTra.setDate(Ngaythue2);
                    System.out.println("avc " + NgayThue1);

                }
            }
        }
    }//GEN-LAST:event_Text_MaDPKeyPressed

    private void Text_MaDPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text_MaDPFocusLost
        // TODO add your handling code here:
        
            String MaDP = Text_MaDP.getText();
            ArrayList<ThuePhong_POJO> dsTP = new ArrayList<ThuePhong_POJO>();
            dsTP = ThuePhong_Controller.getDSThuePhong();
            for (int i = 0; i < dsTP.size(); i++) {
                if (MaDP.equals(dsTP.get(i).getMaThuePhong()) == true) {
                    Combo_MaPhong.setSelectedItem(dsTP.get(i).getMaPhong());
                    Combo_MaKH.setSelectedItem(dsTP.get(i).getMaKH());
                    
                    String ngaythue1 = dsTP.get(i).getNgayTra().toString();
                    String NgayThue1 = dateFormat(ngaythue1);
                    Date Ngaythue2 = new Date(NgayThue1);
                    Date_NgayTra.setDate(Ngaythue2);

                }
            }
        
    }//GEN-LAST:event_Text_MaDPFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_NhapLaiLP;
    private javax.swing.JButton Button_SuaLP;
    private javax.swing.JButton Button_ThemP;
    private javax.swing.JButton Button_TimPT;
    private javax.swing.JButton Button_XoaLP;
    private javax.swing.JComboBox<String> ComboBox_ChonTTPT;
    private javax.swing.JComboBox<String> Combo_MaKH;
    private javax.swing.JComboBox<String> Combo_MaPhong;
    private com.lavantech.gui.comp.DateTimePicker Date_NgayThue;
    private com.lavantech.gui.comp.DateTimePicker Date_NgayTra;
    private javax.swing.JTable Table_Phongthue;
    private javax.swing.JTextField Text_MaDP;
    private javax.swing.JTextField Text_NhapTTTKPT;
    private javax.swing.JTextField Text_mathuephong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
