/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package examples;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Long
 */
public class QuanLyLoaiPhong extends javax.swing.JPanel {
 ArrayList<LoaiPhong_POJO> dsLP;
    /** Creates new form QuanLyLoaiPhong */
    public QuanLyLoaiPhong() {
        initComponents();
        LoadDataToTable();
    }

   public void LoadDataToTable(){
       ArrayList<LoaiPhong_POJO>  dsLP = new ArrayList<LoaiPhong_POJO>();       
        dsLP = LoaiPhong_Controller.getDSLoaiPhong();
        //code gọi
        LoaiPhong_Controller lp = new LoaiPhong_Controller();
        String malp = lp.LayMaLP();
        ////set vào textbox
        Text_LoaiPhong_MaLP.setText(malp);
        
        DefaultTableModel model = (DefaultTableModel) Table_LoaiPhong.getModel();
        Object[] row = new Object[5];
        for (int i = 0 ; i< dsLP.size(); i++){
            row[0] =  dsLP.get(i).getMaLP();
            row[1] =  dsLP.get(i).getLoaiPhong();
            row[2] =  dsLP.get(i).getSoGiuong();
            row[3] =  dsLP.get(i).getDonGia();
            row[4] =  dsLP.get(i).getGhiChu();    
            model.addRow(row);
        }   
   }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        label_MALP = new javax.swing.JLabel();
        label_LP = new javax.swing.JLabel();
        Label_GT = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Text_LoaiPhong_MaLP = new javax.swing.JTextField();
        Text_LoaiPhong_GiaTien = new javax.swing.JTextField();
        Combo_LoaiPhong_SoGiuong = new javax.swing.JComboBox<>();
        Text_LoaiPhong_TenLP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Text_LoaiPhong_GhiChu = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        Button_ThemLP = new javax.swing.JButton();
        Button_XoaLP = new javax.swing.JButton();
        Button_SuaLP = new javax.swing.JButton();
        Button_NhapLaiLP = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        ComboBox_ChonTTLP = new javax.swing.JComboBox<>();
        Text_NhapTTTKLP = new javax.swing.JTextField();
        Button_TimLP = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_LoaiPhong = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUẢN LÝ LOẠI PHÒNG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THÔNG TIN LOẠI PHÒNG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 20))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(740, 230));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home-icon.png"))); // NOI18N

        label_MALP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_MALP.setText("Mã loại phòng");
        label_MALP.setToolTipText("");

        label_LP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_LP.setText("Tên loại phòng");

        Label_GT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_GT.setText("Giá tiền");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Số giường");

        Text_LoaiPhong_MaLP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Text_LoaiPhong_MaLP.setEnabled(false);

        Text_LoaiPhong_GiaTien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Combo_LoaiPhong_SoGiuong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Combo_LoaiPhong_SoGiuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        Text_LoaiPhong_TenLP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Ghi Chú");

        Button_ThemLP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_ThemLP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Plus_000000_25.png"))); // NOI18N
        Button_ThemLP.setText("Thêm");
        Button_ThemLP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_ThemLPMouseClicked(evt);
            }
        });

        Button_XoaLP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_XoaLP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Minus_000000_25.png"))); // NOI18N
        Button_XoaLP.setText("Xóa");
        Button_XoaLP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_XoaLPMouseClicked(evt);
            }
        });

        Button_SuaLP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_SuaLP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Recycling_000000_25.png"))); // NOI18N
        Button_SuaLP.setText("Sửa");
        Button_SuaLP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_SuaLPMouseClicked(evt);
            }
        });

        Button_NhapLaiLP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_NhapLaiLP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Edit_000000_25.png"))); // NOI18N
        Button_NhapLaiLP.setText("Nhập lại");
        Button_NhapLaiLP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_NhapLaiLPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Button_ThemLP, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Button_XoaLP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Button_SuaLP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Button_NhapLaiLP)
                .addGap(12, 12, 12))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_ThemLP)
                    .addComponent(Button_XoaLP)
                    .addComponent(Button_SuaLP)
                    .addComponent(Button_NhapLaiLP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(label_MALP)
                                .addGap(18, 18, 18)
                                .addComponent(Text_LoaiPhong_MaLP))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(label_LP))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Combo_LoaiPhong_SoGiuong, 0, 149, Short.MAX_VALUE)
                                    .addComponent(Text_LoaiPhong_TenLP))))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_GT)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Text_LoaiPhong_GiaTien)
                            .addComponent(Text_LoaiPhong_GhiChu)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_GT, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(label_MALP)
                                .addComponent(Text_LoaiPhong_MaLP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Text_LoaiPhong_GiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_LP)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Text_LoaiPhong_TenLP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(Text_LoaiPhong_GhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Combo_LoaiPhong_SoGiuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setText("Tìm kiếm loại phòng theo:");

        ComboBox_ChonTTLP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComboBox_ChonTTLP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã loại phòng", "Tên loại phòng" }));

        Text_NhapTTTKLP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Button_TimLP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_TimLP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Search_000000_25.png"))); // NOI18N
        Button_TimLP.setText("Tìm kiếm");
        Button_TimLP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_TimLPMouseClicked(evt);
            }
        });

        Table_LoaiPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã loại phòng", "Tên loại phòng", "Số giường", "Giá tiền", "Ghi chú"
            }
        ));
        Table_LoaiPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_LoaiPhongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_LoaiPhong);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBox_ChonTTLP, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Text_NhapTTTKLP, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(Button_TimLP)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ComboBox_ChonTTLP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text_NhapTTTKLP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_TimLP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

   public void resetTable(){
       DefaultTableModel model = (DefaultTableModel) Table_LoaiPhong.getModel();
        model.setRowCount(0);
        LoadDataToTable();
   } 
   

    
    private void Button_ThemLPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_ThemLPMouseClicked
        // TODO add your handling code here:
        String maLP = Text_LoaiPhong_MaLP.getText();
        String tenLP = Text_LoaiPhong_TenLP.getText();
        int soGiuong = Integer.parseInt(Combo_LoaiPhong_SoGiuong.getSelectedItem().toString());
        long gia = Long.parseLong(Text_LoaiPhong_GiaTien.getText());
        String ghiChu= Text_LoaiPhong_GhiChu.getText();
        
        LoaiPhong_POJO LP = new LoaiPhong_POJO(maLP, tenLP, soGiuong, gia, ghiChu);
        
        LoaiPhong_Controller.themLoaiPhong(LP);
        JOptionPane.showMessageDialog(jPanel2, "Thêm Loại Phòng Thành Công!!!");
        resetTable();
    }//GEN-LAST:event_Button_ThemLPMouseClicked

    private void Button_XoaLPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_XoaLPMouseClicked
        // TODO add your handling code here:
       
         String maLP = Text_LoaiPhong_MaLP.getText();
         if (maLP.equals("") == true){
             return;
         }
         else{
         JOptionPane tbXoa = new JOptionPane();
         int t = tbXoa.showConfirmDialog(jPanel2, "Bạn có chắc chắn muốn xóa?", "XÓA",JOptionPane.OK_OPTION);
         if (t == 0){
              LoaiPhong_Controller.xoaLoaiPhong(maLP);
               JOptionPane.showMessageDialog(jPanel2, "Xóa Loại Phòng Thành Công!!!");
               resetTable();
          }     
         }
    }//GEN-LAST:event_Button_XoaLPMouseClicked

    private void Button_SuaLPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_SuaLPMouseClicked
        // TODO add your handling code here:
        String maLP = Text_LoaiPhong_MaLP.getText();
        String tenLP = Text_LoaiPhong_TenLP.getText();
        int soGiuong = Integer.parseInt(Combo_LoaiPhong_SoGiuong.getSelectedItem().toString());
        long gia = Long.parseLong(Text_LoaiPhong_GiaTien.getText());
        String ghiChu= Text_LoaiPhong_GhiChu.getText();
        
         LoaiPhong_POJO LP = new LoaiPhong_POJO(maLP, tenLP, soGiuong, gia, ghiChu);
         
         JOptionPane tbSua = new JOptionPane();
         int t = tbSua.showConfirmDialog(jPanel2, "Bạn có chắc chắn muốn sửa?", "SỬA",JOptionPane.OK_OPTION);
         if (t == 0){
              LoaiPhong_Controller.capNhatLoaiPhong(LP);
               JOptionPane.showMessageDialog(jPanel2, "Sửa Loại Phòng Thành Công!!!","THÔNG BÁO",JOptionPane.INFORMATION_MESSAGE);             
               resetTable();
         }     
        
    }//GEN-LAST:event_Button_SuaLPMouseClicked

    private void Button_NhapLaiLPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_NhapLaiLPMouseClicked
        // TODO add your handling code here:
        Text_LoaiPhong_TenLP.setText("");
        Text_LoaiPhong_GiaTien.setText("");
        Text_LoaiPhong_GhiChu.setText("");
        Combo_LoaiPhong_SoGiuong.setSelectedIndex(0);
    }//GEN-LAST:event_Button_NhapLaiLPMouseClicked

    private void Button_TimLPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_TimLPMouseClicked
        // TODO add your handling code here:
        if (Text_NhapTTTKLP.getText().equals("") == true) {
            resetTable();

        } else {
            if (ComboBox_ChonTTLP.getSelectedItem().equals("Mã loại phòng") == true) {
                String maLP = Text_NhapTTTKLP.getText();
                dsLP = new ArrayList<LoaiPhong_POJO>();
                dsLP = LoaiPhong_Controller.getDSLoaiPhongTheoMa("MaLP", maLP);
                if (dsLP.size() == 0) {
                    JOptionPane.showMessageDialog(null, "Không Có Loại Phòng", "Lỗi", JOptionPane.ERROR_MESSAGE);
                } else {
                    DefaultTableModel model = (DefaultTableModel) Table_LoaiPhong.getModel();
                    Object[] row = new Object[5];
                    model.setRowCount(0);
                    for (int i = 0; i < dsLP.size(); i++) {
                        row[0] = dsLP.get(i).getMaLP();
                        row[1] = dsLP.get(i).getLoaiPhong();
                        row[2] = dsLP.get(i).getSoGiuong();
                        row[3] = dsLP.get(i).getDonGia();
                        row[4] = dsLP.get(i).getGhiChu();
                        model.addRow(row);

                    }
                    JOptionPane.showMessageDialog(jPanel2, "Tìm Thấy Loại Phòng!!!", "THÔNG BÁO", JOptionPane.INFORMATION_MESSAGE);

                }
            }

            if (ComboBox_ChonTTLP.getSelectedItem().equals("Tên loại phòng") == true) {
                String tenLP = Text_NhapTTTKLP.getText();
                dsLP = new ArrayList<LoaiPhong_POJO>();
                dsLP = LoaiPhong_Controller.getDSLoaiPhongTheoMa("LoaiPhong", tenLP);
                if (dsLP.size() == 0) {
                    JOptionPane.showMessageDialog(null, "Không Có Loại Phòng", "Lỗi", JOptionPane.ERROR_MESSAGE);
                } else {
                    DefaultTableModel model = (DefaultTableModel) Table_LoaiPhong.getModel();
                    Object[] row = new Object[5];
                    model.setRowCount(0);
                    for (int i = 0; i < dsLP.size(); i++) {
                        row[0] = dsLP.get(i).getMaLP();
                        row[1] = dsLP.get(i).getLoaiPhong();
                        row[2] = dsLP.get(i).getSoGiuong();
                        row[3] = dsLP.get(i).getDonGia();
                        row[4] = dsLP.get(i).getGhiChu();
                        model.addRow(row);

                    }
                    JOptionPane.showMessageDialog(jPanel2, "Tìm Thấy Loại Phòng!!!", "THÔNG BÁO", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_Button_TimLPMouseClicked

    private void Table_LoaiPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_LoaiPhongMouseClicked
        // TODO add your handling code here:
        int i = Table_LoaiPhong.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) Table_LoaiPhong.getModel();
        Text_LoaiPhong_MaLP.setText(model.getValueAt(i, 0).toString());
        Text_LoaiPhong_TenLP.setText(model.getValueAt(i, 1).toString());
        Combo_LoaiPhong_SoGiuong.setSelectedItem(model.getValueAt(i, 2).toString());
        Text_LoaiPhong_GiaTien.setText(model.getValueAt(i, 3).toString());
        Text_LoaiPhong_GhiChu.setText(model.getValueAt(i, 4).toString());
    }//GEN-LAST:event_Table_LoaiPhongMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_NhapLaiLP;
    private javax.swing.JButton Button_SuaLP;
    private javax.swing.JButton Button_ThemLP;
    private javax.swing.JButton Button_TimLP;
    private javax.swing.JButton Button_XoaLP;
    private javax.swing.JComboBox<String> ComboBox_ChonTTLP;
    private javax.swing.JComboBox<String> Combo_LoaiPhong_SoGiuong;
    private javax.swing.JLabel Label_GT;
    private javax.swing.JTable Table_LoaiPhong;
    private javax.swing.JTextField Text_LoaiPhong_GhiChu;
    private javax.swing.JTextField Text_LoaiPhong_GiaTien;
    private javax.swing.JTextField Text_LoaiPhong_MaLP;
    private javax.swing.JTextField Text_LoaiPhong_TenLP;
    private javax.swing.JTextField Text_NhapTTTKLP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_LP;
    private javax.swing.JLabel label_MALP;
    // End of variables declaration//GEN-END:variables

}
