package examples;
// Generated Dec 24, 2016 1:58:15 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TaiKhoanDangNhap generated by hbm2java
 */
@Entity
@Table(name="TBLTAIKHOANDANGNHAP"
)
public class TaiKhoanDangNhap  implements java.io.Serializable {


     private String MaTK;
     private String MaNV;
     private String LoaiTK;
     private String User;
     private String PassWord;
     private Date NgayTao;

    public TaiKhoanDangNhap() {
    }

	
    public TaiKhoanDangNhap(String MaTK) {
        this.MaTK = MaTK;
    }
    public TaiKhoanDangNhap(String MaTK, String MaNV, String LoaiTK, String User, String PassWord, Date NgayTao) {
       this.MaTK = MaTK;
       this.MaNV = MaNV;
       this.LoaiTK = LoaiTK;
       this.User = User;
       this.PassWord = PassWord;
       this.NgayTao = NgayTao;
    }
   
     @Id 

    
    @Column(name="MATK", nullable=false, length=20)
    public String getMaTK() {
        return this.MaTK;
    }
    
    public void setMaTK(String MaTK) {
        this.MaTK = MaTK;
    }

    
    @Column(name="MANV", length=20)
   
    public String getMaNV(){
        return this.MaNV;
    }
    
    public void setMaNV(String NV){
         this.MaNV = NV;
    }
  

    
    @Column(name="LOAITK", length=50)
    public String getLoaiTK() {
        return this.LoaiTK;
    }
    
    public void setLoaiTK(String LoaiTK) {
        this.LoaiTK = LoaiTK;
    }

    
    @Column(name="USER_DK", length=50)
    public String getUser() {
        return this.User;
    }
    
    public void setUser(String User) {
        this.User = User;
    }

    
    @Column(name="PASSWORD", length=50)
    public String getPassWord() {
        return this.PassWord;
    }
    
    public void setPassWord(String PassWord) {
        this.PassWord = PassWord;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NGTAO", length=0)
    public Date getNgayTao() {
        return this.NgayTao;
    }
    
    public void setNgayTao(Date NgayTao) {
        this.NgayTao = NgayTao;
    }




}


