package examples;
// Generated Dec 24, 2016 1:58:15 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tblnhanvien generated by hbm2java
 */

public class Tblnhanvien {


     private String manv;
     private String tennv;
     private Date ngvl;
     private String diachinv;
     private Date ngsinhnv;
     private String sdtnv;
     private String emailNv;

    public Tblnhanvien() {
    }

	
    public Tblnhanvien(String manv) {
        this.manv = manv;
    }
    public Tblnhanvien(String manv, String tennv, Date ngvl, String diachinv, Date ngsinhnv, String sdtnv, String emailNv) {
       this.manv = manv;
       this.tennv = tennv;
       this.ngvl = ngvl;
       this.diachinv = diachinv;
       this.ngsinhnv = ngsinhnv;
       this.sdtnv = sdtnv;
       this.emailNv = emailNv;
    }
   
   
    public String getManv() {
        return this.manv;
    }
    
    public void setManv(String manv) {
        this.manv = manv;
    }

    
    public String getTennv() {
        return this.tennv;
    }
    
    public void setTennv(String tennv) {
        this.tennv = tennv;
    }

  
    public Date getNgvl() {
        return this.ngvl;
    }
    
    public void setNgvl(Date ngvl) {
        this.ngvl = ngvl;
    }

    
   
    public String getDiachinv() {
        return this.diachinv;
    }
    
    public void setDiachinv(String diachinv) {
        this.diachinv = diachinv;
    }

    
    public Date getNgsinhnv() {
        return this.ngsinhnv;
    }
    
    public void setNgsinhnv(Date ngsinhnv) {
        this.ngsinhnv = ngsinhnv;
    }

    
  
    public String getSdtnv() {
        return this.sdtnv;
    }
    
    public void setSdtnv(String sdtnv) {
        this.sdtnv = sdtnv;
    }

    
   
    public String getEmailNv() {
        return this.emailNv;
    }
    
    public void setEmailNv(String emailNv) {
        this.emailNv = emailNv;
    }




}


