/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examples;

import java.sql.DriverManager;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Dell
 */
public class XuatBaoCaoDoanhThu extends javax.swing.JPanel {

    /**
     * Creates new form XuatBaoCaoDoanhThu
     */
    public XuatBaoCaoDoanhThu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_month = new javax.swing.JComboBox<>();
        txt_year = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Xuất Báo Cáo Doanh Thu Hàng Tháng");
        add(jLabel1);
        jLabel1.setBounds(0, 75, 770, 35);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Xuất báo cáo tháng : ");
        add(jLabel2);
        jLabel2.setBounds(160, 140, 140, 42);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Năm :");
        add(jLabel3);
        jLabel3.setBounds(430, 150, 63, 25);

        txt_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        txt_month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_monthActionPerformed(evt);
            }
        });
        add(txt_month);
        txt_month.setBounds(297, 154, 70, 20);

        txt_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018" }));
        txt_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_yearActionPerformed(evt);
            }
        });
        add(txt_year);
        txt_year.setBounds(487, 154, 76, 20);

        jButton1.setText("Xuất báo cáo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(324, 244, 150, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\V Semester\\UML\\PTTK_KS\\Hình Ảnh\\13441756_1904572756436018_1007432500_o.png")); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4);
        jLabel4.setBounds(0, 0, 770, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_monthActionPerformed

    private void txt_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_yearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
                    
                    String month = txt_month.getSelectedItem().toString();
                    String year = txt_year.getSelectedItem().toString();
                   Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    java.sql.Connection con =(java.sql.Connection) DriverManager.getConnection("jdbc:sqlserver://TUAN_ANH:49612;databaseName=QLKS","sa","123456");
                    
                    Map para = new HashMap();
                    para.put("a", Integer.parseInt(txt_month.getSelectedItem().toString()));
                    para.put("b", Integer.parseInt(txt_year.getSelectedItem().toString()));
                    JasperReport jr =JasperCompileManager.compileReport("D:\\V Semester\\Java\\qlks\\Java_HotelManagement\\src\\examples\\BaoCao.jrxml");
                    JasperPrint jp =JasperFillManager.fillReport(jr,para,con);
                    JasperViewer.viewReport(jp,false);
                }
                catch(Exception f)
                {
                    System.out.print(f);
                }        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> txt_month;
    private javax.swing.JComboBox<String> txt_year;
    // End of variables declaration//GEN-END:variables
}
